function pepato_basic(input_folder, output_folder, body_side, config_params, database_path, muscle_list)
    pepato = PepatoBasic()...
        .init(input_folder, output_folder, body_side, config_params, database_path, muscle_list)...
        .upload_data()...
        .pipeline(4, muscle_list)...
        .write_to_file();
end